# Generated by Django 3.0 on 2020-08-22 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_structure',
            fields=[
                ('assn_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('assn_name', models.CharField(max_length=200)),
                ('assn_description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('author', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment1', models.FileField(blank=True, upload_to=None)),
                ('assignment2', models.FileField(blank=True, upload_to=None)),
                ('assignment3', models.FileField(blank=True, upload_to=None)),
                ('assignment4', models.FileField(blank=True, upload_to=None)),
                ('assignment5', models.FileField(blank=True, upload_to=None)),
                ('assignment6', models.FileField(blank=True, upload_to=None)),
                ('assignment7', models.FileField(blank=True, upload_to=None)),
                ('assignment8', models.FileField(blank=True, upload_to=None)),
                ('status_1', models.BooleanField(default=False)),
                ('status_2', models.BooleanField(default=False)),
                ('status_3', models.BooleanField(default=False)),
                ('status_4', models.BooleanField(default=False)),
                ('status_5', models.BooleanField(default=False)),
                ('status_6', models.BooleanField(default=False)),
                ('status_7', models.BooleanField(default=False)),
                ('status_8', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
