# Generated by Django 3.0.5 on 2020-06-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='assignment3',
            field=models.FileField(blank=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='assignments',
            name='assignment4',
            field=models.FileField(blank=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='assignments',
            name='assignment5',
            field=models.FileField(blank=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='assignments',
            name='assignment6',
            field=models.FileField(blank=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='assignments',
            name='assignment7',
            field=models.FileField(blank=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='assignments',
            name='assignment8',
            field=models.FileField(blank=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='assignments',
            name='status_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignments',
            name='status_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignments',
            name='status_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignments',
            name='status_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignments',
            name='status_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignments',
            name='status_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignments',
            name='status_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignments',
            name='status_8',
            field=models.BooleanField(default=False),
        ),
    ]
