# Generated by Django 3.0.7 on 2020-06-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200612_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_structure',
            fields=[
                ('assn_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('assn_name', models.CharField(max_length=200)),
                ('assn_description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('author', models.CharField(max_length=25)),
            ],
        ),
    ]
